### ISSUE TITLE
快速大幅抖动的时候有马赛克

### ISSUE THREAD

**Issue by DaHuO** [hotkidfamily/iosVTHevcEncoder#2]
我最近在做iOS上的HEVC编码相关项目，但是碰到了问题，就是在画面抖动幅度较大频率较高的时候视频会有马赛克。我用你的demo试了一下，也会有比较明显的马赛克。

特别解释一下，我是将编码后的.h265文件用ffmpeg转成mp4文件播放，会看到马赛克，且ffmpeg转换的过程中会有报错：

<img width="589" alt="screen shot 2017-11-21 at 11 07 22 pm" src="https://user-images.githubusercontent.com/14997081/33162457-8c960b9a-d064-11e7-8cf1-228f313a8120.png">

​

请问对于这个问题你有什么好的解决办法嘛？或者你认为这是iPhone的编码问题，或是ffmpeg的bug嘛？

**Comment by hotkidfamily** [comment]
需要调整码率设置

**Comment by okd4k** [comment]
事实上后来解决这个问题了。和码率无关，是iOS在编码hevc时有概率出现pps_id错误的情况。
